/**
 * RECHTSTEXTE – Impressum, Datenschutz, AGB
 * ------------------------------------------------------------------
 * Impressum übernommen von atex-media.de (Stand 03.09.2026). Datenschutzerklärung und AGB
 * in der Fassung September 2026, eigens für Atex Scale erstellt: Hosting Vercel, Adobe Fonts,
 * Calendly, Wistia (Klick-Facade), Kontaktformular → Close + Resend, WhatsApp-Link,
 * Local Storage „atex-consent“. Bei neuen Diensten Abschnitt ergänzen.
 *
 * Blocktypen: h2 / h3 / h4 = Überschriften, p = Absatz (Zeilenumbrüche
 * mit \n bleiben erhalten, URLs und E-Mails werden automatisch verlinkt).
 */

export type LegalBlock = { type: "h2" | "h3" | "h4" | "p"; text: string };
export type LegalDoc = { title: string; blocks: readonly LegalBlock[] };

export const legal = {
  impressum: {
    title: "Impressum",
    blocks: [
      { type: "h2", text: "Angaben gemäß § 5 TMG" },
      { type: "p", text: "Atex Scale ist eine Marke der Atex Media GmbH." },
      { type: "p", text: "Atex Media GmbH\nKumpfmühler Str. 15\n93047 Regensburg" },
      { type: "p", text: "Handelsregister: HRB19189\nRegistergericht: Regensburg" },
      { type: "p", text: "Vertreten durch:\nDaniel Meier" },
      { type: "h2", text: "Kontakt" },
      { type: "p", text: "Telefon: +49 (0) 176/ 77 88 0548\nE-Mail: info@atex-media.de" },
      { type: "h2", text: "Umsatzsteuer-ID" },
      { type: "p", text: "Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz:\nDE351392033" },
      { type: "h2", text: "EU-Streitschlichtung" },
      { type: "p", text: "Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit: https://ec.europa.eu/consumers/odr/.\nUnsere E-Mail-Adresse finden Sie oben im Impressum." },
      { type: "h2", text: "Verbraucher­streit­beilegung/Universal­schlichtungs­stelle" },
      { type: "p", text: "Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen." },
    ],
  },

  datenschutz: {
    title: "Datenschutzerklärung",
    // Neu erstellt September 2026 für Atex Scale – nennt nur die tatsächlich eingesetzten Dienste
    blocks: [
      { type: "p", text: "Stand: September 2026" },
      { type: "h2", text: "1. Verantwortlicher" },
      { type: "p", text: "Verantwortlich für die Datenverarbeitung auf dieser Webseite ist:\nAtex Media GmbH\nKumpfmühler Str. 15\n93047 Regensburg\nVertreten durch den Geschäftsführer Daniel Meier\nTelefon: +49 (0) 176/ 77 88 0548\nE-Mail: info@atex-media.de" },
      { type: "p", text: "Atex Scale ist eine Marke der Atex Media GmbH. Diese Webseite richtet sich an Unternehmen, die neue Kunden gewinnen wollen." },
      { type: "h2", text: "2. Überblick" },
      { type: "p", text: "Wir verarbeiten personenbezogene Daten nur, soweit dies für den Betrieb der Webseite, die Beantwortung Ihrer Anfragen und die Anbahnung einer Zusammenarbeit erforderlich ist. Rechtsgrundlagen sind Art. 6 Abs. 1 lit. b DSGVO (Vertrag und Vertragsanbahnung), Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse) und, soweit Sie eingewilligt haben, Art. 6 Abs. 1 lit. a DSGVO. Welche Daten wir bei welchem Vorgang verarbeiten, beschreiben die folgenden Abschnitte." },
      { type: "p", text: "Analyse- oder Werbedienste (z. B. Google Analytics, Meta Pixel) setzen wir auf dieser Webseite derzeit nicht ein. Sollten wir solche Dienste künftig einbinden, geschieht das nur nach Ihrer Einwilligung über den Cookie-Hinweis." },
      { type: "h2", text: "3. Hosting und Server-Logfiles" },
      { type: "p", text: "Die Webseite wird bei Vercel Inc., 440 N Barranca Ave #4133, Covina, CA 91723, USA, gehostet. Beim Aufruf der Seite verarbeitet Vercel automatisch Informationen, die Ihr Browser übermittelt: IP-Adresse, Datum und Uhrzeit des Zugriffs, aufgerufene Seite, übertragene Datenmenge, Browsertyp und -version, Betriebssystem sowie die zuvor besuchte Seite (Referrer)." },
      { type: "p", text: "Die Verarbeitung dient der Bereitstellung der Webseite, der Stabilität und der Abwehr von Angriffen. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO. Die Logdaten werden von Vercel nur kurzzeitig gespeichert und nicht mit anderen Daten zusammengeführt. Mit Vercel besteht ein Vertrag zur Auftragsverarbeitung nach Art. 28 DSGVO. Die Übermittlung in die USA stützt sich auf die Standardvertragsklauseln der EU-Kommission (Art. 46 Abs. 2 lit. c DSGVO) und, soweit der Anbieter zertifiziert ist, auf das EU-US Data Privacy Framework." },
      { type: "h2", text: "4. Cookies und lokaler Speicher" },
      { type: "p", text: "Diese Webseite setzt keine Cookies zu Analyse- oder Werbezwecken. Ihre Entscheidung im Cookie-Hinweis speichern wir unter dem Schlüssel „atex-consent“ im lokalen Speicher Ihres Browsers (Local Storage). Dieser Eintrag ist technisch erforderlich, damit der Hinweis nicht bei jedem Seitenaufruf erneut erscheint, und enthält keine personenbezogenen Daten. Rechtsgrundlage ist § 25 Abs. 2 Nr. 2 TDDDG in Verbindung mit Art. 6 Abs. 1 lit. f DSGVO." },
      { type: "p", text: "Sie können Ihre Auswahl jederzeit über die Schaltfläche „Cookies bearbeiten“ unten links auf jeder Seite ändern oder den Eintrag in den Einstellungen Ihres Browsers löschen." },
      { type: "h2", text: "5. Kontaktformular und Anfragen" },
      { type: "p", text: "Wenn Sie über das Formular „Markt-Check anfragen“ oder auf der Kontaktseite eine Anfrage senden, verarbeiten wir die von Ihnen eingegebenen Daten: Name, Unternehmen, Telefonnummer, E-Mail-Adresse, Ihre Einwilligung zur Kontaktaufnahme sowie den Zeitpunkt der Anfrage und die Stelle der Webseite, von der sie ausging. Ein verstecktes Formularfeld dient dem Schutz vor automatisierten Spam-Eingaben; dabei werden keine zusätzlichen Daten gespeichert." },
      { type: "p", text: "Zweck der Verarbeitung ist die Beantwortung Ihrer Anfrage und die Vorbereitung einer möglichen Zusammenarbeit. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (vorvertragliche Maßnahmen) sowie Art. 6 Abs. 1 lit. f DSGVO (Interesse an der Bearbeitung von Anfragen)." },
      { type: "h3", text: "Weitergabe an unser CRM (Close)" },
      { type: "p", text: "Ihre Anfrage wird in unserem Kundenmanagement-System Close gespeichert, betrieben von Elastic Inc. (Close), San Francisco, USA. Dort legen wir Ihr Unternehmen als Kontakt mit den Angaben aus dem Formular an. Mit dem Anbieter besteht ein Vertrag zur Auftragsverarbeitung nach Art. 28 DSGVO; die Übermittlung in die USA ist durch die Standardvertragsklauseln der EU-Kommission abgesichert." },
      { type: "h3", text: "Benachrichtigung per E-Mail (Resend)" },
      { type: "p", text: "Über jede Anfrage werden wir intern per E-Mail benachrichtigt. Den Versand übernimmt der Dienst Resend, betrieben von Resend Inc., San Francisco, USA. Die E-Mail enthält die Angaben aus dem Formular. Mit dem Anbieter besteht ein Vertrag zur Auftragsverarbeitung; die Übermittlung in die USA ist durch die Standardvertragsklauseln der EU-Kommission abgesichert." },
      { type: "h3", text: "Speicherdauer" },
      { type: "p", text: "Wir speichern Ihre Anfrage, solange dies für die Bearbeitung erforderlich ist. Kommt eine Zusammenarbeit zustande, bewahren wir die Daten im Rahmen der gesetzlichen Aufbewahrungsfristen (in der Regel sechs bzw. zehn Jahre) auf. Kommt keine Zusammenarbeit zustande, löschen wir die Anfrage spätestens zwölf Monate nach dem letzten Kontakt." },
      { type: "h2", text: "6. Terminbuchung über Calendly" },
      { type: "p", text: "Auf der Kontaktseite und über das Terminfenster unten rechts können Sie ein Erstgespräch buchen. Dafür binden wir den Dienst Calendly ein, betrieben von Calendly LLC, 115 E Main St, Ste A1B, Buford, GA 30518, USA. Beim Aufruf der Kontaktseite lädt Ihr Browser den Kalender von den Servern von Calendly; dabei werden Ihre IP-Adresse und Browserinformationen an Calendly übermittelt." },
      { type: "p", text: "Wenn Sie einen Termin buchen, verarbeitet Calendly die von Ihnen eingegebenen Daten (Name, E-Mail-Adresse, gewählter Termin, optionale Angaben) und übermittelt sie an uns. Rechtsgrundlage für die Einbindung ist Art. 6 Abs. 1 lit. f DSGVO (einfache Terminvereinbarung), für die Buchung Art. 6 Abs. 1 lit. b DSGVO. Die Übermittlung in die USA stützt sich auf die Standardvertragsklauseln der EU-Kommission und, soweit der Anbieter zertifiziert ist, auf das EU-US Data Privacy Framework. Weitere Informationen: https://calendly.com/privacy" },
      { type: "h2", text: "7. Videos (Wistia)" },
      { type: "p", text: "Die Kundenstimme auf dieser Webseite wird über den Dienst Wistia bereitgestellt, betrieben von Wistia Inc., 17 Tudor Street, Cambridge, MA 02139, USA. Das Video wird erst geladen, wenn Sie auf die Abspielfläche klicken. Bis dahin wird keine Verbindung zu Wistia hergestellt." },
      { type: "p", text: "Mit dem Klick willigen Sie ein, dass Ihr Browser eine Verbindung zu Wistia aufbaut und Wistia Ihre IP-Adresse sowie Informationen zur Wiedergabe verarbeitet und gegebenenfalls Cookies setzt. Rechtsgrundlage ist Ihre Einwilligung nach Art. 6 Abs. 1 lit. a DSGVO und § 25 Abs. 1 TDDDG. Die Übermittlung in die USA stützt sich auf die Standardvertragsklauseln der EU-Kommission. Weitere Informationen: https://wistia.com/privacy" },
      { type: "h2", text: "8. Schriftarten (Adobe Fonts)" },
      { type: "p", text: "Für eine einheitliche Darstellung nutzen wir Schriftarten von Adobe Fonts. Anbieter ist Adobe Systems Software Ireland Limited, 4-6 Riverwalk, Citywest Business Campus, Dublin 24, Irland. Beim Aufruf der Seite lädt Ihr Browser die Schriften von den Servern von Adobe; dabei wird Ihre IP-Adresse übermittelt. Nach Angaben von Adobe werden dabei keine Cookies gesetzt." },
      { type: "p", text: "Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse liegt in einem einheitlichen und gut lesbaren Schriftbild. Soweit Daten an Adobe Inc. in die USA übermittelt werden, stützt sich dies auf die Standardvertragsklauseln der EU-Kommission und das EU-US Data Privacy Framework. Weitere Informationen: https://www.adobe.com/de/privacy/policies/adobe-fonts.html" },
      { type: "h2", text: "9. Kontakt per WhatsApp" },
      { type: "p", text: "Auf der Webseite finden Sie eine Schaltfläche, die eine Nachricht an uns in WhatsApp vorbereitet. Beim bloßen Anzeigen der Seite werden keine Daten an WhatsApp übermittelt. Erst wenn Sie die Schaltfläche anklicken, öffnet sich WhatsApp; ab dann gelten die Datenschutzbestimmungen von WhatsApp Ireland Limited, 4 Grand Canal Square, Dublin 2, Irland (Teil von Meta). Wir verarbeiten die dort mit Ihnen ausgetauschten Nachrichten zur Beantwortung Ihrer Anfrage auf Grundlage von Art. 6 Abs. 1 lit. b und lit. f DSGVO. Weitere Informationen: https://www.whatsapp.com/legal/privacy-policy-eea" },
      { type: "h2", text: "10. Links zu anderen Webseiten" },
      { type: "p", text: "Diese Webseite enthält Links zu anderen Webseiten, etwa zu atex-media.de, zu Karriereseiten und zu sozialen Netzwerken. Beim Anklicken verlassen Sie unsere Webseite; für die dortige Datenverarbeitung ist der jeweilige Anbieter verantwortlich. Allein durch die Anzeige unserer Seite werden keine Daten an diese Anbieter übermittelt." },
      { type: "h2", text: "11. Datensicherheit" },
      { type: "p", text: "Die Webseite wird ausschließlich verschlüsselt über HTTPS (TLS) ausgeliefert. Auch das Kontaktformular überträgt Ihre Angaben verschlüsselt. Wir treffen technische und organisatorische Maßnahmen, um Ihre Daten gegen Verlust, Manipulation und unbefugten Zugriff zu schützen." },
      { type: "h2", text: "12. Ihre Rechte" },
      { type: "p", text: "Sie haben gegenüber uns folgende Rechte hinsichtlich der Sie betreffenden personenbezogenen Daten:\n– Recht auf Auskunft (Art. 15 DSGVO)\n– Recht auf Berichtigung (Art. 16 DSGVO)\n– Recht auf Löschung (Art. 17 DSGVO)\n– Recht auf Einschränkung der Verarbeitung (Art. 18 DSGVO)\n– Recht auf Datenübertragbarkeit (Art. 20 DSGVO)\n– Recht auf Widerruf einer erteilten Einwilligung mit Wirkung für die Zukunft (Art. 7 Abs. 3 DSGVO)" },
      { type: "p", text: "Widerspruchsrecht: Soweit wir Ihre Daten auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO verarbeiten, können Sie dieser Verarbeitung aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit widersprechen (Art. 21 DSGVO). Wir verarbeiten die Daten dann nicht weiter, es sei denn, wir können zwingende schutzwürdige Gründe nachweisen, die Ihre Interessen überwiegen." },
      { type: "p", text: "Zur Ausübung Ihrer Rechte genügt eine formlose Nachricht an info@atex-media.de. Sie haben außerdem das Recht, sich bei einer Datenschutz-Aufsichtsbehörde zu beschweren. Für uns zuständig ist das Bayerische Landesamt für Datenschutzaufsicht (BayLDA), Promenade 18, 91522 Ansbach, www.lda.bayern.de." },
      { type: "h2", text: "13. Keine automatisierte Entscheidungsfindung" },
      { type: "p", text: "Eine automatisierte Entscheidungsfindung oder ein Profiling im Sinne von Art. 22 DSGVO findet auf dieser Webseite nicht statt." },
      { type: "h2", text: "14. Änderungen dieser Datenschutzerklärung" },
      { type: "p", text: "Wir passen diese Datenschutzerklärung an, wenn sich die Rechtslage oder die auf der Webseite eingesetzten Dienste ändern. Es gilt jeweils die hier veröffentlichte Fassung." },
    ],
  },

  agb: {
    title: "Allgemeine Geschäftsbedingungen",
    // Stand September 2026 – Teil A (Allgemein), B (Recruiting), C (Website), D (Neukundengewinnung)
    blocks: [
      { type: "h2", text: "Teil A – Allgemeine Bestimmungen" },
      { type: "h3", text: "§ 1 Geltungsbereich" },
      { type: "p", text: "(1) Diese Allgemeinen Geschäftsbedingungen (AGB) gelten für alle Verträge zwischen der Atex Media GmbH, Kumpfmühler Straße 15, 93047 Regensburg („Atex\") und ihren Auftraggebern. Atex schließt Verträge ausschließlich mit Unternehmern im Sinne des § 14 BGB, juristischen Personen des öffentlichen Rechts oder öffentlich-rechtlichen Sondervermögen." },
      { type: "p", text: "(2) Die AGB bestehen aus diesem Teil A sowie den Besonderen Bedingungen Teil B (Recruiting / Bewerbervermittlung), Teil C (Website) und Teil D (Neukundengewinnung). Welcher Besondere Teil gilt, ergibt sich aus der im Angebot genannten Leistungskategorie. Enthält ein Angebot Leistungen mehrerer Kategorien, gelten die jeweiligen Besonderen Teile nebeneinander." },
      { type: "p", text: "(3) Bei Widersprüchen gilt folgende Rangfolge: individuelle Vereinbarung im Angebot, Besonderer Teil B/C/D, dieser Teil A." },
      { type: "p", text: "(4) Abweichende Geschäftsbedingungen des Auftraggebers finden keine Anwendung, auch wenn Atex ihnen nicht ausdrücklich widerspricht." },
      { type: "h3", text: "§ 2 Angebot und Vertragsschluss" },
      { type: "p", text: "(1) Angebote von Atex sind für die im Angebot genannte Frist bindend; fehlt eine Angabe, fünf Kalendertage ab Angebotsdatum." },
      { type: "p", text: "(2) Der Vertrag kommt durch Annahme des Angebots in Textform (§ 126b BGB, E-Mail genügt) oder durch Unterzeichnung zustande. Mit Vertragsschluss erkennt der Auftraggeber diese AGB als verbindlich an." },
      { type: "p", text: "(3) Mündliche Nebenabreden bestehen nicht. Änderungen und Ergänzungen des Vertrags bedürfen der Textform." },
      { type: "h3", text: "§ 3 Leistungen" },
      { type: "p", text: "(1) Umfang und Inhalt der Leistungen ergeben sich aus dem angenommenen Angebot in Verbindung mit dem jeweiligen Besonderen Teil dieser AGB." },
      { type: "p", text: "(2) Soweit im Besonderen Teil nichts anderes bestimmt ist, schuldet Atex ein Tätigwerden nach den Regeln der Kunst, keinen bestimmten wirtschaftlichen Erfolg." },
      { type: "p", text: "(3) Atex darf zur Leistungserbringung Subunternehmer und Freelancer einsetzen und bleibt für deren Leistung verantwortlich." },
      { type: "p", text: "(4) Nachträgliche Änderungen oder Erweiterungen des Leistungsumfangs werden gesondert in Textform vereinbart und nach dem im Angebot genannten Stundensatz oder, falls nicht genannt, mit 120 € netto je Stunde vergütet. Atex ist nicht verpflichtet, Zusatzleistungen zu erbringen, bevor sie vereinbart sind." },
      { type: "h3", text: "§ 4 Mitwirkung des Auftraggebers" },
      { type: "p", text: "(1) Der Auftraggeber stellt alle für die Leistung erforderlichen Informationen, Inhalte, Zugänge und Entscheidungen rechtzeitig, vollständig und in nutzbarer digitaler Form bereit und benennt einen entscheidungsbefugten Ansprechpartner." },
      { type: "p", text: "(2) Der Auftraggeber stellt sicher, dass von ihm gelieferte Inhalte (Texte, Bilder, Videos, Logos, Daten) frei von Rechten Dritter sind und geltendem Recht entsprechen. Er stellt Atex von Ansprüchen Dritter frei, die auf solchen Inhalten beruhen, einschließlich angemessener Rechtsverteidigungskosten." },
      { type: "p", text: "(3) Verzögerungen oder Mehraufwände durch fehlende, verspätete oder fehlerhafte Mitwirkung gehen nicht zu Lasten von Atex. Vereinbarte Fristen verlängern sich entsprechend; die Vergütung bleibt unberührt. Nachweisbarer Mehraufwand wird nach § 3 Abs. 4 vergütet." },
      { type: "h3", text: "§ 5 Vergütung, Rechnungsstellung, Fälligkeit" },
      { type: "p", text: "(1) Die Vergütung ergibt sich aus dem Angebot. Alle Preise verstehen sich netto zuzüglich gesetzlicher Umsatzsteuer." },
      { type: "p", text: "(2) Die erste Rechnung wird zum vereinbarten Onboarding-Termin gestellt. Nimmt der Auftraggeber den Onboarding-Termin nicht wahr oder verschiebt er ihn weniger als zwei Werktage vor dem Termin, gilt der ursprünglich vereinbarte Termin als Rechnungsdatum. Atex bietet in diesem Fall einen Ersatztermin an. Weitere Rechnungen werden nach dem im Angebot genannten Zahlungsplan gestellt." },
      { type: "p", text: "(3) Rechnungen sind ohne Abzug innerhalb des im Angebot genannten Zahlungsziels fällig; fehlt eine Angabe, innerhalb von 14 Tagen ab Rechnungsdatum." },
      { type: "p", text: "(4) Bei Zahlungsverzug gelten die gesetzlichen Verzugszinsen (§ 288 Abs. 2 BGB) und die gesetzliche Verzugspauschale. Atex ist berechtigt, die Leistungserbringung bis zum Zahlungseingang auszusetzen; vereinbarte Fristen und Laufzeiten verlängern sich entsprechend. Eine Aussetzung nach diesem Absatz gilt nicht als Leistungsstörung von Atex." },
      { type: "p", text: "(5) Der Auftraggeber kann nur mit unbestrittenen oder rechtskräftig festgestellten Forderungen aufrechnen. Zurückbehaltungsrechte stehen ihm nur wegen Gegenansprüchen aus demselben Vertrag zu." },
      { type: "p", text: "(6) Fremdkosten (z. B. Werbebudgets, Hosting, Domains, Lizenzen, Stockmaterial) sind in der Vergütung nicht enthalten, soweit das Angebot nichts anderes ausweist. Sie werden im Angebot oder im Besonderen Teil ausgewiesen und vom Auftraggeber zusätzlich getragen." },
      { type: "h3", text: "§ 6 Nutzungsrechte und Referenz" },
      { type: "p", text: "(1) Mit vollständiger Zahlung der vereinbarten Vergütung erhält der Auftraggeber an den für ihn erstellten Arbeitsergebnissen ein einfaches, zeitlich und räumlich unbeschränktes Nutzungsrecht für den vertraglich vorgesehenen Zweck. Bis zur vollständigen Zahlung ist die Nutzung nur widerruflich gestattet." },
      { type: "p", text: "(2) Nicht übertragen werden Rechte an Konzepten, Entwürfen, Vorlagen, Code-Bibliotheken, Workflows und Know-how von Atex sowie an Komponenten Dritter (z. B. Templates, Schriften, Plugins, Plattform-Bestandteile). Für Komponenten Dritter gelten deren Lizenzbedingungen." },
      { type: "p", text: "(3) Atex darf den Auftraggeber mit Namen und Logo als Referenz nennen und die erbrachten Leistungen (z. B. Website, Stellenanzeigen, Kampagnenergebnisse in anonymisierter oder mit dem Auftraggeber abgestimmter Form) auf eigenen Kanälen darstellen. Der Auftraggeber kann dem aus wichtigem Grund in Textform widersprechen; Atex stellt die Nutzung dann binnen 14 Tagen ein. Eine abweichende Regelung kann im Angebot vereinbart werden." },
      { type: "h3", text: "§ 7 Laufzeit und Kündigung" },
      { type: "p", text: "(1) Der Vertrag läuft für die im Angebot vereinbarte Laufzeit bzw. bis zur Fertigstellung des vereinbarten Projekts. Eine ordentliche Kündigung während dieser Zeit ist ausgeschlossen, soweit der Besondere Teil nichts anderes bestimmt." },
      { type: "p", text: "(2) Das Kündigungsrecht nach § 627 BGB ist ausgeschlossen. Das Recht zur außerordentlichen Kündigung aus wichtigem Grund bleibt unberührt." },
      { type: "p", text: "(3) Ein wichtiger Grund für Atex liegt insbesondere vor, wenn der Auftraggeber mit einer Zahlung trotz Mahnung und Nachfrist von zehn Tagen in Verzug ist oder ein Projekt nach § 9 länger als sechs Monate ruht." },
      { type: "p", text: "(4) Bei einer Kündigung aus einem Grund, den der Auftraggeber zu vertreten hat, gelten für die Vergütung die Regelungen des jeweiligen Besonderen Teils." },
      { type: "h3", text: "§ 8 Freigaben" },
      { type: "p", text: "(1) Atex stellt Inhalte, Entwürfe und Kampagnen zur Freigabe bereit. Der Auftraggeber prüft und gibt frei oder teilt Änderungswünsche innerhalb von drei Werktagen ab Bereitstellung in Textform mit." },
      { type: "p", text: "(2) Änderungswünsche werden im vereinbarten Umfang (Korrekturschleifen laut Angebot, sonst eine Korrekturschleife je Bereitstellung) umgesetzt; weitergehende Änderungen sind Zusatzleistungen nach § 3 Abs. 4." },
      { type: "p", text: "(3) Erfolgt innerhalb der Frist keine Rückmeldung, gilt die Bereitstellung als freigegeben, sofern Atex bei der Bereitstellung auf die Frist und diese Folge ausdrücklich hingewiesen hat." },
      { type: "h3", text: "§ 9 Ruhendstellung bei ausbleibender Mitwirkung" },
      { type: "p", text: "(1) Kann Atex eine Leistung nicht fortsetzen, weil eine Mitwirkung des Auftraggebers nach § 4 oder dem Besonderen Teil fehlt (insbesondere Zugänge, Inhalte, Entscheidungen, Terminwahrnehmung), erinnert Atex den Auftraggeber in Textform mit einer Frist von mindestens drei Werktagen. § 8 Abs. 3 bleibt für freigabefähige Bereitstellungen unberührt." },
      { type: "p", text: "(2) Bleiben drei aufeinanderfolgende Erinnerungen ohne Rückmeldung und hat Atex in der dritten Erinnerung auf die Ruhendstellung hingewiesen, kann Atex das Projekt ruhend stellen. Die Ruhendstellung wird dem Auftraggeber in Textform mitgeteilt." },
      { type: "p", text: "(3) Während des Ruhens ist Atex von der Leistungspflicht befreit. Laufende Maßnahmen (z. B. Kampagnen) darf Atex anhalten. Vereinbarte Laufzeiten, Fristen und Garantiezeiträume verlängern sich um die Dauer des Ruhens. Die Vergütung wird nach dem vereinbarten Zahlungsplan weiter fällig. Das Ruhen gilt nicht als Leistungsstörung von Atex und nicht als eigenmächtiges Anhalten durch den Auftraggeber im Sinne des Teils B." },
      { type: "p", text: "(4) Holt der Auftraggeber die Mitwirkung vollständig nach, nimmt Atex die Leistung nach Maßgabe freier Kapazitäten wieder auf, spätestens acht Wochen nach vollständiger Nachholung. Ist im Angebot eine Reaktivierungspauschale vereinbart, wird sie mit der Wiederaufnahme fällig." },
      { type: "p", text: "(5) Ruht ein Projekt länger als sechs Monate, kann Atex den Vertrag außerordentlich kündigen; die Vergütungsfolgen richten sich nach dem Besonderen Teil." },
      { type: "h3", text: "§ 10 Kein Widerrufsrecht" },
      { type: "p", text: "Ein Widerrufsrecht besteht nicht, da Verträge ausschließlich mit Unternehmern geschlossen werden." },
      { type: "h3", text: "§ 11 Datenschutz und Vertraulichkeit" },
      { type: "p", text: "(1) Beide Parteien beachten die geltenden Datenschutzvorschriften. Soweit Atex personenbezogene Daten im Auftrag des Auftraggebers verarbeitet (insbesondere Bewerber- und Interessentendaten), schließen die Parteien vor Beginn der Verarbeitung einen Auftragsverarbeitungsvertrag nach Art. 28 DSGVO. Atex stellt hierfür eine Vorlage bereit." },
      { type: "p", text: "(2) Der Auftraggeber ist für die Rechtmäßigkeit der Datenverarbeitung auf seinen eigenen Websites und Kanälen verantwortlich, insbesondere für Datenschutzerklärung, Impressum und Einwilligungsmanagement (Consent-Banner), sofern Atex dies nicht ausdrücklich als Leistung übernommen hat." },
      { type: "p", text: "(3) Beide Parteien behandeln als vertraulich gekennzeichnete oder erkennbar vertrauliche Informationen der anderen Partei vertraulich, auch über das Vertragsende hinaus." },
      { type: "h3", text: "§ 12 Haftung" },
      { type: "p", text: "(1) Atex haftet unbeschränkt bei Vorsatz und grober Fahrlässigkeit, bei Verletzung von Leben, Körper oder Gesundheit, nach dem Produkthaftungsgesetz, bei arglistig verschwiegenen Mängeln sowie im Umfang einer ausdrücklich übernommenen Garantie." },
      { type: "p", text: "(2) Bei einfacher Fahrlässigkeit haftet Atex nur bei Verletzung wesentlicher Vertragspflichten (Pflichten, deren Erfüllung die ordnungsgemäße Durchführung des Vertrags erst ermöglicht und auf deren Einhaltung der Auftraggeber regelmäßig vertrauen darf), begrenzt auf den vorhersehbaren, vertragstypischen Schaden." },
      { type: "p", text: "(3) Atex haftet nicht für Ausfälle, Änderungen, Sperrungen oder Richtlinien von Plattformen und Diensten Dritter (z. B. Meta, Google, Webflow, Hosting-Anbieter), soweit Atex diese nicht zu vertreten hat." },
      { type: "p", text: "(4) Im Übrigen ist die Haftung ausgeschlossen. Die Einschränkungen gelten auch für Mitarbeiter, Vertreter und Subunternehmer von Atex." },
      { type: "h3", text: "§ 13 Schlussbestimmungen" },
      { type: "p", text: "(1) Es gilt das Recht der Bundesrepublik Deutschland unter Ausschluss des UN-Kaufrechts." },
      { type: "p", text: "(2) Ausschließlicher Gerichtsstand für alle Streitigkeiten aus oder im Zusammenhang mit dem Vertrag ist Regensburg, sofern der Auftraggeber Kaufmann, juristische Person des öffentlichen Rechts oder öffentlich-rechtliches Sondervermögen ist." },
      { type: "p", text: "(3) Sollte eine Bestimmung dieser AGB unwirksam sein oder werden, bleibt die Wirksamkeit der übrigen Bestimmungen unberührt." },
      { type: "p", text: "(4) Atex kann diese AGB für künftige Verträge ändern. Für bestehende Verträge gilt die bei Vertragsschluss gültige Fassung." },
      { type: "h2", text: "Teil B – Besondere Bedingungen Recruiting / Bewerbervermittlung" },
      { type: "h3", text: "B § 1 Leistungsgegenstand" },
      { type: "p", text: "(1) Atex erbringt Leistungen zur Gewinnung von Bewerbern für die im Angebot genannten Stellenprofile („Bewerbervermittlung\"). Dazu gehören insbesondere die Erstellung und Aussteuerung von Stellenanzeigen und Werbemaßnahmen, die Vorstellung geeigneter Kandidaten aus dem Bewerberpool von Atex sowie die Bereitstellung eines Bewerbermanagement-Systems." },
      { type: "p", text: "(2) Atex schuldet ein Tätigwerden nach den Regeln der Kunst (Dienstvertrag). Ein bestimmter Erfolg ist nur geschuldet, soweit im Angebot eine Garantie nach B § 4 ausdrücklich vereinbart ist." },
      { type: "p", text: "(3) Kanäle, Gestaltung, Zielgruppen und Budgetverteilung liegen im fachlichen Ermessen von Atex. Vorgaben des Auftraggebers zu CI-Farben, Schrift und Logo werden beachtet." },
      { type: "h3", text: "B § 2 Werbebudget" },
      { type: "p", text: "(1) Das Werbebudget für Anzeigenschaltungen ist nicht Teil des Honorars und wird im Angebot gesondert ausgewiesen. Die dort genannte Höhe ist ein Erfahrungswert; Atex kann das Budget nach Abstimmung mit dem Auftraggeber anpassen, wenn dies zur Zielerreichung erforderlich ist." },
      { type: "p", text: "(2) Die Anzeigen laufen über das Werbekonto von Atex. Atex stellt das verbrauchte Werbebudget monatlich in Rechnung oder ruft es nach dem im Angebot genannten Modus ab. Auf Wunsch des Auftraggebers und nach Vereinbarung kann ein Werbekonto des Auftraggebers verwendet werden; Atex benötigt dann uneingeschränkten Zugriff für die Laufzeit." },
      { type: "p", text: "(3) Der Auftraggeber darf Kampagnen, Werbekonten, Budgets oder Zugänge während der Laufzeit nicht eigenmächtig anhalten, kürzen oder löschen. Ein Anhalten durch Atex nach A § 5 Abs. 4 oder A § 9 gilt nicht als eigenmächtiges Anhalten des Auftraggebers." },
      { type: "h3", text: "B § 3 Begriffe" },
      { type: "p", text: "(1) Qualifizierte Bewerbung: eine Bewerbung, die über die von Atex eingerichteten Kanäle eingeht oder von Atex aus dem Bewerberpool vorgestellt oder vom Auftraggeber nach B § 6 Abs. 2 i) im Bewerbermanagement-System hinterlegt wird, und deren Bewerber die im Onboarding gemeinsam festgelegten Mindestanforderungen erfüllt und vollständige Kontaktdaten angegeben hat." },
      { type: "p", text: "(2) Einstellung: das Vorliegen eines von beiden Seiten unterzeichneten Arbeits- oder Ausbildungsvertrags mit einem Bewerber, der während der Laufzeit oder Karenzzeit über die Kanäle nach Abs. 1 erfasst wurde – unabhängig von Berufsbezeichnung, Eintrittsdatum, Standort und davon, ob der Bewerber dem Auftraggeber zuvor bereits bekannt war. Maßgeblich für die Zählung ist die Markierung als „eingestellt\" im Bewerbermanagement-System; der Auftraggeber nimmt diese Markierung unverzüglich vor." },
      { type: "p", text: "(3) Erstlaufzeit: die im Angebot vereinbarte Laufzeit der Bewerbervermittlung." },
      { type: "p", text: "(4) Karenzzeit: der Zeitraum der kostenfreien Verlängerung nach B § 4 Abs. 3." },
      { type: "h3", text: "B § 4 Garantie" },
      { type: "p", text: "(1) Geltung. Eine Garantie auf eine bestimmte Anzahl qualifizierter Bewerbungen oder Einstellungen besteht nur, wenn sie im Angebot ausdrücklich als „Garantie\" bezeichnet ist. Garantieart, Anzahl und Karenzzeit ergeben sich aus dem Angebot." },
      { type: "p", text: "(2) Garantiezeitraum. Die Garantie gilt für die Erstlaufzeit. Alle in der Erstlaufzeit erzielten qualifizierten Bewerbungen bzw. Einstellungen werden angerechnet." },
      { type: "p", text: "(3) Karenzzeit. Wird das Garantieziel in der Erstlaufzeit nicht erreicht, verlängert Atex die Betreuung ohne zusätzliches Honorar um die im Angebot genannte Karenzzeit, höchstens jedoch um sechs Monate. In der Karenzzeit erzielte qualifizierte Bewerbungen bzw. Einstellungen werden angerechnet. Die Karenzzeit endet vorzeitig mit Erreichen des Garantieziels." },
      { type: "p", text: "(4) Werbebudget in der Karenzzeit. Der Auftraggeber verpflichtet sich, während der Karenzzeit ein Werbebudget von insgesamt mindestens 1.200 € netto bereitzustellen. Die Bereitstellung erfolgt nach Wahl des Auftraggebers durch Zahlung an Atex zur Verwendung im Atex-Werbekonto oder durch Freigabe eines entsprechenden Budgets in einem von Atex gesteuerten Werbekonto des Auftraggebers. Das Budget ist zu Beginn der Karenzzeit bereitzustellen; Atex kann eine Aufteilung in monatliche Teilbeträge anbieten. Ein höheres Budget kann im Angebot vereinbart werden." },
      { type: "p", text: "(5) Rechtsfolge. Mit Ablauf der Karenzzeit ist die Garantie erfüllt. Weitergehende Ansprüche des Auftraggebers, insbesondere auf Rückzahlung oder Schadensersatz, bestehen nicht. Abweichend hiervon kann im Angebot anstelle der Karenzzeit eine anteilige Rückzahlung je nicht erreichter Einheit in dort festgelegter Höhe vereinbart werden." },
      { type: "p", text: "(6) Beginn der Karenzzeit. Die Karenzzeit beginnt automatisch mit dem Tag nach Ablauf der Erstlaufzeit, wenn das Garantieziel bis dahin nicht erreicht ist; einer Erklärung des Auftraggebers bedarf es nicht. Atex teilt dem Auftraggeber den Beginn der Karenzzeit und die Höhe des nach Abs. 4 bereitzustellenden Werbebudgets in Textform mit." },
      { type: "h3", text: "B § 5 Voraussetzungen und Erlöschen der Garantie" },
      { type: "p", text: "(1) Die Garantie und die Karenzzeit setzen voraus, dass der Auftraggeber seine Mitwirkungspflichten nach B § 6 vollständig erfüllt, eine marktgerechte Stellenausschreibung mit realistischen Anforderungen und Gehaltsangaben ermöglicht und alle fälligen Rechnungen fristgerecht bezahlt." },
      { type: "p", text: "(2) Die Garantie erlischt, soweit der Auftraggeber eine Voraussetzung nach Abs. 1 oder eine Mitwirkungspflicht nach B § 6 verletzt und dies für das Nichterreichen des Garantieziels ursächlich oder mitverursachend ist." },
      { type: "p", text: "(3) Unabhängig von Abs. 2 erlischt die Garantie für das betroffene Stellenprofil, wenn der Auftraggeber" },
      { type: "p", text: "a) im Zeitraum der Zusammenarbeit im selben Einzugsgebiet für dieselbe Stellengruppe eine eigene oder durch Dritte geschaltete bezahlte Werbekampagne (z. B. Meta, Google, LinkedIn, Jobportale mit Performance-Abrechnung) betreibt, ohne dies vorher mit Atex abzustimmen;" },
      { type: "p", text: "b) Kampagnen, Werbekonten, Budgets oder Zugänge entgegen B § 2 Abs. 3 eigenmächtig anhält, kürzt oder löscht;" },
      { type: "p", text: "c) mit einer fälligen Zahlung trotz Mahnung und Nachfrist von zehn Tagen in Verzug ist;" },
      { type: "p", text: "d) das Werbebudget nach B § 4 Abs. 4 nicht, nicht vollständig oder nicht rechtzeitig bereitstellt. In diesem Fall endet die Karenzzeit mit dem Tag, an dem das Budget ausgeschöpft ist oder hätte bereitgestellt werden müssen." },
      { type: "p", text: "(4) Ruht das Projekt nach A § 9, verlängern sich Erstlaufzeit und Karenzzeit um die Ruhezeit." },
      { type: "h3", text: "B § 6 Mitwirkungspflichten" },
      { type: "p", text: "(1) Die Mitwirkung des Auftraggebers ist wesentlicher Bestandteil der Leistung. A § 4 gilt ergänzend." },
      { type: "p", text: "(2) Der Auftraggeber verpflichtet sich insbesondere zu:" },
      { type: "p", text: "a) vollständigem Durchlaufen des Onboardings einschließlich gemeinsamer Festlegung der Mindestanforderungen je Stellenprofil und Bereitstellung von Unternehmensinformationen, Bildern und Logo in nutzbarer digitaler Form;" },
      { type: "p", text: "b) Zustimmung zur Veröffentlichung von Gehaltsangaben im im Onboarding besprochenen Umfang;" },
      { type: "p", text: "c) Einräumung kreativer Gestaltungsfreiheit nach B § 1 Abs. 3;" },
      { type: "p", text: "d) Freigabe von Inhalten und Kampagnen nach A § 8;" },
      { type: "p", text: "e) Sichtung und Bearbeitung eingehender Bewerbungen innerhalb von zwei Werktagen sowie fortlaufender Pflege des Bewerberstatus im Bewerbermanagement-System;" },
      { type: "p", text: "f) nachvollziehbarer Dokumentation jeder Einschätzung oder Ablehnung eines Bewerbers mit aussagekräftiger Begründung im Bewerbermanagement-System;" },
      { type: "p", text: "g) telefonischem Erstkontakt zu jedem zugeführten Bewerber mit mindestens drei dokumentierten Kontaktversuchen; Lebenslauf und weitere Unterlagen werden frühestens zum Vorstellungsgespräch angefordert;" },
      { type: "p", text: "h) Rückmeldung an jeden Bewerber innerhalb von 72 Stunden mit nachvollziehbarer Begründung;" },
      { type: "p", text: "i) Meldung und Erfassung von Bewerbern im Bewerbermanagement-System, die sich infolge der Maßnahmen von Atex auf anderem Weg (z. B. direkt per E-Mail, Telefon oder Website) beim Auftraggeber melden;" },
      { type: "p", text: "j) Teilnahme an vereinbarten Abstimmungsterminen (z. B. Onboarding, Videodreh, Zwischenbilanz)." },
      { type: "p", text: "(3) Verzögerungen und Mehraufwände durch fehlende Mitwirkung regelt A § 4 Abs. 3; die Ruhendstellung A § 9." },
      { type: "h3", text: "B § 7 Prüfrecht" },
      { type: "p", text: "Atex darf die Einhaltung der Voraussetzungen nach B § 5 und der Mitwirkungspflichten nach B § 6 prüfen, insbesondere durch Einsicht in das Bewerbermanagement-System und die dort hinterlegte Dokumentation. Der Auftraggeber erteilt hierzu auf Verlangen Auskunft, auch bis zu drei Monate nach Vertragsende. Eine Kontaktaufnahme von Atex zu Bewerbern zu Prüfzwecken erfolgt nur mit Zustimmung des Auftraggebers und im Rahmen des Auftragsverarbeitungsvertrags." },
      { type: "h3", text: "B § 8 Datenschutz" },
      { type: "p", text: "(1) Soweit Atex Bewerberdaten für den Auftraggeber verarbeitet (Erfassung, Weiterleitung, Bewerbermanagement-System), handelt Atex als Auftragsverarbeiter. Vor Beginn der Verarbeitung wird ein Auftragsverarbeitungsvertrag nach Art. 28 DSGVO geschlossen (A § 11 Abs. 1)." },
      { type: "p", text: "(2) Bewerber, die Atex aus dem eigenen Bewerberpool vorstellt, werden von Atex in eigener datenschutzrechtlicher Verantwortung erfasst. Die Übermittlung an den Auftraggeber erfolgt nur mit Einwilligung des Bewerbers oder auf anderer Rechtsgrundlage. Mit Übermittlung wird der Auftraggeber für die weitere Verarbeitung eigener Verantwortlicher." },
      { type: "p", text: "(3) Der Auftraggeber stellt sicher, dass Bewerberdaten nach Abschluss des Verfahrens fristgerecht gelöscht werden, soweit keine Einwilligung zur längeren Speicherung vorliegt." },
      { type: "h3", text: "B § 9 Karriereseite und optionale Bestandteile" },
      { type: "p", text: "(1) Ist im Angebot eine Karriereseite, ein Kurzbewerbungsformular oder eine Stellenanzeige als Bestandteil der Bewerbervermittlung vereinbart, stellt Atex diese für die Laufzeit einschließlich Karenzzeit bereit. Für Gestaltung und Abnahme gilt A § 8." },
      { type: "p", text: "(2) Nach Ende der Laufzeit kann der Auftraggeber die Karriereseite gegen die im Angebot genannte monatliche Vergütung weiter nutzen. Ohne eine solche Vereinbarung ist Atex berechtigt, die Karriereseite nach Laufzeitende offline zu nehmen. Nutzungsrechte an Inhalten richten sich nach A § 6." },
      { type: "h3", text: "B § 10 Vergütung bei vorzeitiger Beendigung" },
      { type: "p", text: "Endet der Vertrag vor Ablauf der Erstlaufzeit aus einem Grund, den der Auftraggeber zu vertreten hat (insbesondere außerordentliche Kündigung durch Atex nach A § 7 Abs. 3), bleibt der Anspruch von Atex auf das Honorar für die gesamte Erstlaufzeit bestehen. Angerechnet werden ersparte Aufwendungen, insbesondere nicht verbrauchtes Werbebudget und nicht angefallene Fremdkosten; das Honorar selbst gilt als Vergütung für die reservierte Kapazität. Eine Garantie und Karenzzeit entfallen. Bereits gezahltes Honorar wird nicht zurückerstattet." },
      { type: "h2", text: "Teil C – Besondere Bedingungen Website" },
      { type: "h3", text: "C § 1 Leistungsgegenstand" },
      { type: "p", text: "(1) Atex erstellt die im Angebot beschriebene Website (Seitenanzahl, Funktionen, Sprachen, Plattform). Nicht im Angebot genannte Seiten, Funktionen, Integrationen, Texte, Bildmaterial, Übersetzungen, rechtliche Texte (Impressum, Datenschutzerklärung), Consent-Management und laufende Pflege sind nicht Bestandteil, soweit nicht ausdrücklich aufgeführt." },
      { type: "p", text: "(2) Atex schuldet die Herstellung der Website nach dem freigegebenen Konzept und Design (Werkvertrag). Suchmaschinenplatzierungen, Besucherzahlen oder Umsatzsteigerungen sind nicht geschuldet." },
      { type: "p", text: "(3) Die Website wird auf der im Angebot genannten Plattform (z. B. Webflow) erstellt. Für die Plattform gelten deren Nutzungsbedingungen. Atex haftet nicht für Funktionsänderungen, Ausfälle oder Preisänderungen der Plattform." },
      { type: "h3", text: "C § 2 Projektablauf und Phasen" },
      { type: "p", text: "(1) Das Projekt gliedert sich in die Phasen Onboarding, Strategie und Konzeption (Anforderungen, Struktur, Inhalte), Design (Mock-up), Entwicklung und Livegang. Der im Angebot genannte Zeitplan ist eine Planung; verbindliche Termine bedürfen der ausdrücklichen Vereinbarung in Textform." },
      { type: "p", text: "(2) Jede Phase wird durch Freigabe des Auftraggebers nach A § 8 abgeschlossen. Mit Freigabe einer Phase sind Änderungen an ihren Ergebnissen (z. B. Struktur nach Freigabe des Designs) Zusatzleistungen nach A § 3 Abs. 4." },
      { type: "p", text: "(3) Der Auftraggeber liefert Texte, Bilder und sonstige Inhalte spätestens zum im Onboarding vereinbarten Termin, andernfalls setzt Atex Platzhalter oder Standardinhalte ein und der Zeitplan verschiebt sich entsprechend. A § 9 (Ruhendstellung) gilt." },
      { type: "h3", text: "C § 3 Abnahme" },
      { type: "p", text: "(1) Nach Fertigstellung stellt Atex die Website zur Abnahme bereit. Der Auftraggeber prüft innerhalb von fünf Werktagen und erklärt die Abnahme oder teilt wesentliche Mängel in Textform mit." },
      { type: "p", text: "(2) Die Website gilt als abgenommen, wenn der Auftraggeber innerhalb der Frist keine wesentlichen Mängel rügt und Atex bei Bereitstellung auf diese Folge hingewiesen hat, oder wenn der Auftraggeber die Website produktiv nutzt oder den Livegang freigibt." },
      { type: "p", text: "(3) Unwesentliche Mängel berechtigen nicht zur Verweigerung der Abnahme; sie werden im Rahmen der Gewährleistung behoben." },
      { type: "h3", text: "C § 4 Gewährleistung" },
      { type: "p", text: "(1) Atex gewährleistet, dass die Website zum Zeitpunkt der Abnahme die vereinbarte Beschaffenheit hat und in den zu diesem Zeitpunkt aktuellen Versionen der gängigen Browser (Chrome, Safari, Firefox, Edge) funktioniert." },
      { type: "p", text: "(2) Die Gewährleistungsfrist beträgt zwölf Monate ab Abnahme. Atex leistet nach eigener Wahl Nachbesserung oder Neuherstellung. Schlägt die Nacherfüllung zweimal fehl, stehen dem Auftraggeber die gesetzlichen Rechte zu." },
      { type: "p", text: "(3) Keine Gewährleistung besteht für Fehler, die auf Änderungen des Auftraggebers oder Dritter, auf Änderungen der Plattform, von Browsern oder Drittdiensten oder auf vom Auftraggeber gelieferte Inhalte zurückgehen." },
      { type: "h3", text: "C § 5 Hosting, Domain, Drittkosten, Zugänge" },
      { type: "p", text: "(1) Hosting und Domain werden vom Auftraggeber direkt beim jeweiligen Anbieter beauftragt und bezahlt, soweit das Angebot nichts anderes vorsieht. Atex weist die voraussichtlichen Kosten im Angebot aus (Erfahrungswert). Preisänderungen der Anbieter gehen nicht zu Lasten von Atex." },
      { type: "p", text: "(2) Die Plattform-Zugänge (z. B. Webflow-Workspace, Domain-Registrar) werden so eingerichtet, dass der Auftraggeber nach vollständiger Zahlung Inhaber ist. Bis zur vollständigen Zahlung verbleibt die Website im Zugriff von Atex." },
      { type: "p", text: "(3) Laufende Pflege, Updates, Inhaltsänderungen und Support nach Livegang sind nur im Rahmen einer gesondert vereinbarten Betreuung geschuldet." },
      { type: "h3", text: "C § 6 Vergütung, Fälligkeit, keine Rückerstattung" },
      { type: "p", text: "(1) Die Vergütung ist ein Festpreis und wird vollständig zum vereinbarten Onboarding-Termin fällig (A § 5 Abs. 2), soweit das Angebot keinen anderen Zahlungsplan vorsieht. Die Vorleistung des Auftraggebers ist sachlich begründet: Atex reserviert mit dem Onboarding verbindlich Team-Kapazität für das Projekt und beginnt unmittelbar mit Konzeption und Umsetzung." },
      { type: "p", text: "(2) Für die Berechnung nach Abs. 5 gelten folgende Leistungsanteile am Festpreis: Onboarding, Strategie und Konzeption (Zielgruppe, Seitenstruktur, Inhaltskonzept, Gestaltungsgrundlage) 60 %; Design (Mock-up) 25 %; Entwicklung, Einrichtung und Livegang 15 %. Ein Anteil gilt als erbracht, sobald die Phase zur Freigabe oder Abnahme bereitgestellt wurde. Die Gewichtung entspricht dem Aufwand von Atex: Der wesentliche Wert der Leistung entsteht in Konzeption und Design; die technische Umsetzung erfolgt weitgehend auf Basis der Konzeption mit vorbereiteten Systemen." },
      { type: "p", text: "(3) Der Vertrag ist für beide Seiten bis zur Abnahme verbindlich. Das freie Kündigungsrecht des Auftraggebers nach § 648 Satz 1 BGB ist ausgeschlossen. Das Recht zur außerordentlichen Kündigung aus wichtigem Grund bleibt unberührt." },
      { type: "p", text: "(4) Die gezahlte Vergütung vergütet die Leistungen aller Phasen sowie die dafür reservierte Kapazität von Atex und wird nicht zurückerstattet – auch dann nicht, wenn der Auftraggeber das Projekt nicht fortführt, Inhalte nicht liefert, die Website nicht nutzt oder den Livegang nicht freigibt." },
      { type: "p", text: "(5) Beendet der Auftraggeber den Vertrag dennoch vor Abnahme oder kündigt Atex aus einem vom Auftraggeber zu vertretenden Grund (A § 7 Abs. 3, A § 9 Abs. 5), behält Atex die volle vereinbarte Vergütung abzüglich der Aufwendungen, die Atex infolge der Beendigung erspart oder durch anderweitige Verwendung der freigewordenen Kapazität erwirbt. Es wird vermutet, dass diese Ersparnis 20 % der auf die noch nicht erbrachten Leistungsanteile nach Abs. 2 entfallenden Vergütung beträgt; beiden Parteien bleibt der Nachweis einer höheren oder niedrigeren Ersparnis vorbehalten. Eine Rückerstattung erfolgt nur in Höhe der so berechneten Ersparnis." },
      { type: "p", text: "(6) Ruht das Projekt nach A § 9, bleibt die Vergütung in voller Höhe bei Atex; mit Wiederaufnahme wird eine im Angebot vereinbarte Reaktivierungspauschale fällig." },
      { type: "h3", text: "C § 7 Nutzungsrechte und Kennzeichnung" },
      { type: "p", text: "(1) Mit vollständiger Zahlung erhält der Auftraggeber das Nutzungsrecht nach A § 6 an Design, Layout und individuell erstellten Inhalten der Website. Der Auftraggeber darf die Website bearbeiten, erweitern und durch Dritte pflegen lassen." },
      { type: "p", text: "(2) Atex ist berechtigt, im Footer der Website einen dezenten Hinweis „Website von Atex Media\" mit Link zu setzen. Der Auftraggeber kann dem in Textform widersprechen; der Hinweis wird dann entfernt." },
      { type: "p", text: "(3) Für Schriften, Stockmaterial, Plugins und sonstige Komponenten Dritter gelten deren Lizenzen; Atex weist im Angebot oder bei Übergabe aus, welche Lizenzen der Auftraggeber selbst halten oder fortführen muss." },
      { type: "h2", text: "Teil D – Besondere Bedingungen Neukundengewinnung" },
      { type: "h3", text: "D § 1 Leistungsgegenstand" },
      { type: "p", text: "(1) Atex plant, erstellt und steuert Werbekampagnen und zugehörige Funnel-Bestandteile (z. B. Anzeigen, Creatives, Landingpages, Formulare, Tracking) zur Gewinnung von Anfragen, Leads oder Terminen für den Auftraggeber, wie im Angebot beschrieben." },
      { type: "p", text: "(2) Atex schuldet ein Tätigwerden nach den Regeln der Kunst (Dienstvertrag). Eine bestimmte Anzahl von Leads, Anfragen, Terminen, Abschlüssen oder ein bestimmter Umsatz ist nicht geschuldet, soweit nicht im Angebot ausdrücklich eine Garantie vereinbart ist; für eine solche Garantie gelten B § 4 und B § 5 entsprechend." },
      { type: "p", text: "(3) Kanäle, Gestaltung, Zielgruppen, Gebotsstrategien und Budgetverteilung liegen im fachlichen Ermessen von Atex. Vorgaben des Auftraggebers zu CI, rechtlich erforderlichen Angaben und ausgeschlossenen Aussagen werden beachtet." },
      { type: "h3", text: "D § 2 Werbebudget und Werbekonten" },
      { type: "p", text: "(1) Das Werbebudget ist nicht Teil des Honorars und wird im Angebot gesondert ausgewiesen. B § 2 Abs. 1 und 3 gelten entsprechend." },
      { type: "p", text: "(2) Die Kampagnen laufen über das Werbekonto von Atex; Atex stellt das verbrauchte Werbebudget monatlich in Rechnung oder ruft es nach dem im Angebot genannten Modus ab. Nach Vereinbarung kann ein Werbekonto des Auftraggebers verwendet werden, das dieser mit eigener Zahlungsmethode hinterlegt und für das er Atex für die Laufzeit vollen Zugriff einräumt; der Auftraggeber bleibt dann Vertragspartner der Plattform und trägt das Werbebudget direkt." },
      { type: "p", text: "(3) Sperrungen, Einschränkungen oder Ablehnungen durch die Plattform (z. B. wegen Richtlinien, Verifizierungen, Zahlungsproblemen) liegen außerhalb des Einflussbereichs von Atex. Atex unterstützt bei der Behebung im Rahmen des vereinbarten Umfangs; Laufzeiten verlängern sich um die Dauer der Einschränkung, soweit der Auftraggeber sie zu vertreten hat." },
      { type: "h3", text: "D § 3 Mitwirkungspflichten" },
      { type: "p", text: "(1) A § 4 gilt. Der Auftraggeber verpflichtet sich insbesondere zu:" },
      { type: "p", text: "a) vollständigem Durchlaufen des Onboardings (Angebot, Zielgruppe, Alleinstellungsmerkmale, Preise, Einzugsgebiet, Ausschlüsse);" },
      { type: "p", text: "b) Bereitstellung von Zugängen zu Werbekonten, Unternehmensseiten, Website/Landingpage, Analyse- und Tracking-Tools sowie zum verwendeten CRM;" },
      { type: "p", text: "c) Freigabe von Anzeigen, Creatives und Landingpages nach A § 8;" },
      { type: "p", text: "d) Bearbeitung eingehender Anfragen innerhalb von einem Werktag und Rückmeldung zum Status (erreicht, Termin, Abschluss, nicht qualifiziert) im vereinbarten System, damit Atex die Kampagnen optimieren kann;" },
      { type: "p", text: "e) Sicherstellung von Impressum, Datenschutzerklärung und Einwilligungsmanagement auf eigenen Seiten (A § 11 Abs. 2), einschließlich der Einwilligung für Tracking-Pixel und Conversion-Messung;" },
      { type: "p", text: "f) Unterlassung eigener oder durch Dritte geschalteter bezahlter Kampagnen für dasselbe Angebot im selben Einzugsgebiet ohne Abstimmung mit Atex, da diese Auslieferung und Messung verfälschen." },
      { type: "p", text: "(2) A § 4 Abs. 3 (Verzögerungen) und A § 9 (Ruhendstellung) gelten." },
      { type: "h3", text: "D § 4 Laufzeit, Reporting, Beendigung" },
      { type: "p", text: "(1) Die Laufzeit ergibt sich aus dem Angebot. Atex stellt in dem dort vereinbarten Rhythmus ein Reporting über Ausgaben, Reichweite und Ergebnisse bereit." },
      { type: "p", text: "(2) Endet der Vertrag vor Ablauf der Laufzeit aus einem Grund, den der Auftraggeber zu vertreten hat, gilt B § 10 entsprechend." },
      { type: "p", text: "(3) Mit Vertragsende übergibt Atex die Werbekonten, Kampagnenstrukturen und Zielgruppen im Konto des Auftraggebers in dem Zustand, in dem sie sich befinden. Creatives und Landingpages unterliegen A § 6; Vorlagen, Kampagnen-Setups und Optimierungslogiken von Atex bleiben Know-how von Atex." },
      { type: "h3", text: "D § 5 Datenschutz" },
      { type: "p", text: "(1) Soweit Atex Lead- oder Interessentendaten für den Auftraggeber verarbeitet (z. B. Formulare, CRM-Anbindung, Lead-Weiterleitung), handelt Atex als Auftragsverarbeiter; A § 11 Abs. 1 gilt." },
      { type: "p", text: "(2) Der Auftraggeber ist für die rechtskonforme Ansprache der gewonnenen Leads (insbesondere Werbeeinwilligung nach § 7 UWG bei E-Mail oder Telefon) allein verantwortlich." },
      { type: "p", text: "Atex Media GmbH · Kumpfmühler Straße 15 · 93047 Regensburg · Stand: September 2026" },
    ],
  },
} as const satisfies Record<string, LegalDoc>;
